# Airbnb - Data Visualizations Project

## Investor Approach

In [1]:
# First of all, we need to import pandas library
import pandas as pd

# Then we can try to read the CSV file for the first time
df = pd.read_csv('../listings.csv')
df.info()
df.head(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32665 entries, 0 to 32664
Data columns (total 85 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            32665 non-null  int64
 1   listing_url                                   32665 non-null  object
 2   scrape_id                                     32665 non-null  int64
 3   last_searched                                 25834 non-null  object
 4   last_scraped                                  32665 non-null  object
 5   source                                        32665 non-null  object
 6   name                                          32665 non-null  object
 7   description                                   32099 non-null  object
 8   neighborhood_overview                         14310 non-null  object
 9   picture_url                                   32665 non-null  object
 10  host_id                                       32665 non-null  int64
 11  host_url                                      32665 non-null  object
 12  host_name                                     32658 non-null  object
 13  host_since                                    32658 non-null  object
 14  host_location                                 22601 non-null  object
 15  host_about                                    13097 non-null  object
 16  host_response_time                            26507 non-null  object
 17  host_response_rate                            26507 non-null  object
 18  host_acceptance_rate                          28062 non-null  object
 19  host_is_superhost                             32267 non-null  object
 20  host_thumbnail_url                            32658 non-null  object
 21  host_picture_url                              32658 non-null  object
 22  host_neighbourhood                            24330 non-null  object
 23  host_listings_count                           32658 non-null  float64
 24  host_total_listings_count                     32658 non-null  float64
 25  host_verifications                            32658 non-null  object
 26  host_has_profile_pic                          32658 non-null  object
 27  host_identity_verified                        32658 non-null  object
 28  neighbourhood                                 14310 non-null  object
 29  latitude                                      32665 non-null  float64
 30  longitude                                     32665 non-null  float64
 31  property_type                                 32665 non-null  object
 32  room_type                                     32665 non-null  object
 33  accommodates                                  32665 non-null  int64
 34  bathrooms                                     25806 non-null  float64
 35  bathrooms_text                                32600 non-null  object
 36  bedrooms                                      30043 non-null  float64
 37  beds                                          25807 non-null  float64
 38  amenities                                     32665 non-null  object
 39  price                                         25820 non-null  object
 40  minimum_nights                                32665 non-null  int64
 41  maximum_nights                                32665 non-null  int64
 42  minimum_minimum_nights                        32643 non-null  float64
 43  maximum_minimum_nights                        32643 non-null  float64
 44  minimum_maximum_nights                        32643 non-null  float64
 45  maximum_maximum_nights                        32643 non-null  float64
 46  minimum_nights_avg_ntm                        32665 non-null  float64
 47  maximum_nights_avg_ntm                        32665 non-null  float64
 48  calendar_updated                              0 non-null      float64
 49  has_availability                              31388 non-null  object
 50  availability_30                               32665 non-null  int64
 51  availability_60                               32665 non-null  int64
 52  availability_90                               32665 non-null  int64
 53  availability_365                              32665 non-null  int64
 54  calendar_last_scraped                         32665 non-null  object
 55  number_of_reviews                             32665 non-null  int64
 56  number_of_reviews_ltm                         32665 non-null  int64
 57  number_of_reviews_l30d                        32665 non-null  int64
 58  availability_eoy                              32665 non-null  int64
 59  number_of_reviews_ly                          32665 non-null  int64
 60  estimated_occupancy_l365d                     32665 non-null  int64
 61  estimated_revenue_l365d                       25820 non-null  float64
 62  first_review                                  28857 non-null  object
 63  last_review                                   28857 non-null  object
 64  review_scores_rating                          28857 non-null  float64
 65  review_scores_accuracy                        28855 non-null  float64
 66  review_scores_cleanliness                     28855 non-null  float64
 67  review_scores_checkin                         28852 non-null  float64
 68  review_scores_communication                   28856 non-null  float64
 69  review_scores_location                        28852 non-null  float64
 70  review_scores_value                           28850 non-null  float64
 71  requires_license                              0 non-null      float64
 72  license                                       0 non-null      float64
 73  instant_bookable                              32665 non-null  object
 74  calculated_host_listings_count                32665 non-null  int64
 75  calculated_host_listings_count_entire_homes   32665 non-null  int64
 76  calculated_host_listings_count_private_rooms  32665 non-null  int64
 77  calculated_host_listings_count_shared_rooms   32665 non-null  int64
 78  region_id                                     32665 non-null  int64
 79  region_name                                   32665 non-null  object
 80  region_parent_id                              32665 non-null  int64
 81  region_parent_name                            32665 non-null  object
 82  region_parent_parent_id                       32665 non-null  object
 83  region_parent_parent_name                     32665 non-null  object
 84  reviews_per_month                             28857 non-null  float64
dtypes: float64(25), int64(22), object(38)
memory usage: 21.2+ MB

,id,listing_url,scrape_id,last_searched,last_scraped,source,name,description,neighborhood_overview,picture_url,...,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,region_id,region_name,region_parent_id,region_parent_name,region_parent_parent_id,region_parent_parent_name,reviews_per_month
0,11532,https://www.airbnb.com/rooms/11532,20250926033914,2025-09-26,2025-09-27,country scrape,The Red Door Westport,The Red Door Westport is a beautiful four bedr...,The Red Door is set in a quiet and peaceful lo...,https://a0.muscache.com/pictures/79987707-39fa...,...,2,0,0,13150404,Westport LEA-4,155001,Mayo County Council,IE042,West,0.72
1,36950,https://www.airbnb.com/rooms/36950,20250926033914,2025-09-26,2025-09-27,country scrape,Bunratty Castle Mews Guesthouse,NaN,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,...,0,1,0,1330402,Shannon LEA-7,35001,Clare County Council,IE051,Mid-West,2.87
2,40176,https://www.airbnb.com/rooms/40176,20250926033914,2025-09-26,2025-09-27,country scrape,Galway Hideaway - Connemara Cottage,A perfectly peaceful base from which to explor...,The peace and tranquility of the mountain we l...,https://a0.muscache.com/pictures/miso/Hosting-...,...,1,0,0,1360406,Conamara South LEA-5,65001,Galway County Council,IE042,West,2.90
3,42037,https://www.airbnb.com/rooms/42037,20250926033914,NaN,2025-09-27,previous scrape,Cozy room in Lisdoonvarna - near Cliffs of Moher,Enjoy a stay in your private garden-view room ...,I live in a quiet neighbourhood which is nonet...,https://a0.muscache.com/pictures/cff94fa5-21f4...,...,0,1,0,1330400,Ennistimon LEA-4,35001,Clare County Council,IE051,Mid-West,0.80
4,43280,https://www.airbnb.com/rooms/43280,20250926033914,2025-09-26,2025-09-26,country scrape,Cozy Comfortable Double Bedroom & ensuite,Nadia and I will do our best to make sure you ...,We have a lovely home in a quiet area in the h...,https://a0.muscache.com/pictures/500b0c32-2471...,...,0,2,0,1390401,Kilkenny LEA-7,95001,Kilkenny County Council,IE052,South-East,5.37

In [2]:
# Before we start our analysis, let's remove any unnecessary columns
# Test if columns exist before dropping them
columns_to_drop = ['scrape_id', 'last_scraped', 'source', 'minimum_minimum_nights', 'maximum_minimum_nights', 'minimum_maximum_nights', 'maximum_maximum_nights', 'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm', 'requires_license', 'license', 'region_id', 'region_parent_id', 'region_parent_parent_id', 'region_parent_parent_name']
existing_columns_to_drop = [col for col in columns_to_drop if col in df.columns]
df = df.drop(columns=existing_columns_to_drop)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32665 entries, 0 to 32664
Data columns (total 70 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            32665 non-null  int64
 1   listing_url                                   32665 non-null  object
 2   last_searched                                 25834 non-null  object
 3   name                                          32665 non-null  object
 4   description                                   32099 non-null  object
 5   neighborhood_overview                         14310 non-null  object
 6   picture_url                                   32665 non-null  object
 7   host_id                                       32665 non-null  int64
 8   host_url                                      32665 non-null  object
 9   host_name                                     32658 non-null  object
 10  host_since                                    32658 non-null  object
 11  host_location                                 22601 non-null  object
 12  host_about                                    13097 non-null  object
 13  host_response_time                            26507 non-null  object
 14  host_response_rate                            26507 non-null  object
 15  host_acceptance_rate                          28062 non-null  object
 16  host_is_superhost                             32267 non-null  object
 17  host_thumbnail_url                            32658 non-null  object
 18  host_picture_url                              32658 non-null  object
 19  host_neighbourhood                            24330 non-null  object
 20  host_listings_count                           32658 non-null  float64
 21  host_total_listings_count                     32658 non-null  float64
 22  host_verifications                            32658 non-null  object
 23  host_has_profile_pic                          32658 non-null  object
 24  host_identity_verified                        32658 non-null  object
 25  neighbourhood                                 14310 non-null  object
 26  latitude                                      32665 non-null  float64
 27  longitude                                     32665 non-null  float64
 28  property_type                                 32665 non-null  object
 29  room_type                                     32665 non-null  object
 30  accommodates                                  32665 non-null  int64
 31  bathrooms                                     25806 non-null  float64
 32  bathrooms_text                                32600 non-null  object
 33  bedrooms                                      30043 non-null  float64
 34  beds                                          25807 non-null  float64
 35  amenities                                     32665 non-null  object
 36  price                                         25820 non-null  object
 37  minimum_nights                                32665 non-null  int64
 38  maximum_nights                                32665 non-null  int64
 39  calendar_updated                              0 non-null      float64
 40  has_availability                              31388 non-null  object
 41  availability_30                               32665 non-null  int64
 42  availability_60                               32665 non-null  int64
 43  availability_90                               32665 non-null  int64
 44  availability_365                              32665 non-null  int64
 45  calendar_last_scraped                         32665 non-null  object
 46  number_of_reviews                             32665 non-null  int64
 47  number_of_reviews_ltm                         32665 non-null  int64
 48  number_of_reviews_l30d                        32665 non-null  int64
 49  availability_eoy                              32665 non-null  int64
 50  number_of_reviews_ly                          32665 non-null  int64
 51  estimated_occupancy_l365d                     32665 non-null  int64
 52  estimated_revenue_l365d                       25820 non-null  float64
 53  first_review                                  28857 non-null  object
 54  last_review                                   28857 non-null  object
 55  review_scores_rating                          28857 non-null  float64
 56  review_scores_accuracy                        28855 non-null  float64
 57  review_scores_cleanliness                     28855 non-null  float64
 58  review_scores_checkin                         28852 non-null  float64
 59  review_scores_communication                   28856 non-null  float64
 60  review_scores_location                        28852 non-null  float64
 61  review_scores_value                           28850 non-null  float64
 62  instant_bookable                              32665 non-null  object
 63  calculated_host_listings_count                32665 non-null  int64
 64  calculated_host_listings_count_entire_homes   32665 non-null  int64
 65  calculated_host_listings_count_private_rooms  32665 non-null  int64
 66  calculated_host_listings_count_shared_rooms   32665 non-null  int64
 67  region_name                                   32665 non-null  object
 68  region_parent_name                            32665 non-null  object
 69  reviews_per_month                             28857 non-null  float64
dtypes: float64(17), int64(19), object(34)
memory usage: 17.4+ MB

In [3]:
# Check the unique values in the 'region_parent_name' column
df['region_parent_name'].unique()

array(['Mayo County Council', 'Clare County Council',
       'Galway County Council', 'Kilkenny County Council',
       'Dun Laoghaire-rathdown County Council', 'Sligo County Council',
       'Cavan County Council', 'Cork County Council',
       'Roscommon County Council', 'Wicklow County Council',
       'Kerry County Council', 'Dublin City Council',
       'Donegal County Council', 'Limerick City And County Council',
       'Carlow County Council', 'South Dublin County Council',
       'Kildare County Council', 'Tipperary County Council',
       'Galway City Council', 'Meath County Council',
       'Longford County Council', 'Westmeath County Council',
       'Offaly County Council', 'Wexford County Council',
       'Monaghan County Council', 'Waterford City And County Council',
       'Fingal County Council', 'Cork City Council',
       'Leitrim County Council', 'Louth County Council',
       'Laois County Council'], dtype=object)

In [4]:
# Lets do some data manipulation to transform the 'region_parent_name' into counties
df['region_parent_name'] = df['region_parent_name'].str.replace('City And County Council', '').str.strip()
df['region_parent_name'] = df['region_parent_name'].str.replace('County Council', '').str.strip()
df['region_parent_name'] = df['region_parent_name'].str.replace('City Council', '').str.strip()
df['region_parent_name'] = df['region_parent_name'].str.replace('South Dublin', 'Dublin').str.strip()
df['region_parent_name'] = df['region_parent_name'].str.replace('Dun Laoghaire-rathdown', 'Dublin').str.strip()

# Check the unique values in the 'county' column
df['region_parent_name'].unique()

array(['Mayo', 'Clare', 'Galway', 'Kilkenny', 'Dublin', 'Sligo', 'Cavan',
       'Cork', 'Roscommon', 'Wicklow', 'Kerry', 'Donegal', 'Limerick',
       'Carlow', 'Kildare', 'Tipperary', 'Meath', 'Longford', 'Westmeath',
       'Offaly', 'Wexford', 'Monaghan', 'Waterford', 'Fingal', 'Leitrim',
       'Louth', 'Laois'], dtype=object)

In [5]:
# Peek at the cleaned dataset
df.head(5)

,id,listing_url,last_searched,name,description,neighborhood_overview,picture_url,host_id,host_url,host_name,...,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,region_name,region_parent_name,reviews_per_month
0,11532,https://www.airbnb.com/rooms/11532,2025-09-26,The Red Door Westport,The Red Door Westport is a beautiful four bedr...,The Red Door is set in a quiet and peaceful lo...,https://a0.muscache.com/pictures/79987707-39fa...,42928,https://www.airbnb.com/users/show/42928,Tracy,...,4.88,4.83,f,2,2,0,0,Westport LEA-4,Mayo,0.72
1,36950,https://www.airbnb.com/rooms/36950,2025-09-26,Bunratty Castle Mews Guesthouse,NaN,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,159447,https://www.airbnb.com/users/show/159447,Dolores,...,4.85,4.79,f,1,0,1,0,Shannon LEA-7,Clare,2.87
2,40176,https://www.airbnb.com/rooms/40176,2025-09-26,Galway Hideaway - Connemara Cottage,A perfectly peaceful base from which to explor...,The peace and tranquility of the mountain we l...,https://a0.muscache.com/pictures/miso/Hosting-...,172429,https://www.airbnb.com/users/show/172429,Brian,...,4.79,4.72,t,1,1,0,0,Conamara South LEA-5,Galway,2.90
3,42037,https://www.airbnb.com/rooms/42037,NaN,Cozy room in Lisdoonvarna - near Cliffs of Moher,Enjoy a stay in your private garden-view room ...,I live in a quiet neighbourhood which is nonet...,https://a0.muscache.com/pictures/cff94fa5-21f4...,182682,https://www.airbnb.com/users/show/182682,Karin,...,4.86,4.88,f,1,0,1,0,Ennistimon LEA-4,Clare,0.80
4,43280,https://www.airbnb.com/rooms/43280,2025-09-26,Cozy Comfortable Double Bedroom & ensuite,Nadia and I will do our best to make sure you ...,We have a lovely home in a quiet area in the h...,https://a0.muscache.com/pictures/500b0c32-2471...,188930,https://www.airbnb.com/users/show/188930,Corey And Nadia,...,4.95,4.95,f,2,0,2,0,Kilkenny LEA-7,Kilkenny,5.37

In [6]:
# Check for missing values
missing_values = df['price'].isnull().sum()
print(f"Missing values in 'price': {missing_values} ({missing_values/len(df)*100:.2f}%)")

# Step 3: Check data type
print(f"Data type of 'price': {df['price'].dtype}")

Missing values in 'price': 6845 (20.96%)
Data type of 'price': object

In [7]:
# Let's fill any missing values in the 'price' column with 0
df['price'] = df['price'].fillna(0)

In [8]:
# Check for non-numeric values (strings with '$' or commas)
non_numeric = df['price'].apply(lambda x: not isinstance(x, (int, float)) and pd.notnull(x))
if non_numeric.any():
    print("Non-numeric values found in 'price':")
    print(df[non_numeric]['price'].head())
    # Clean price column if needed (remove '$', commas, and convert to float)
    df['price'] = df['price'].replace(r'[\$,]', '', regex=True).astype(float)
    print("Cleaned 'price' column to numeric format.")

Non-numeric values found in 'price':
0    $558.00
1    $110.00
2    $131.00
4     $72.00
5     $74.00
Name: price, dtype: object
Cleaned 'price' column to numeric format.

In [9]:
print(f"Data type of 'price': {df['price'].dtype}")

Data type of 'price': float64

In [10]:
# Let's drop any rows where 'price' is less than or equal to 0
# But let'set's first check how many such rows exist
invalid_price_count = (df['price'] <= 0).sum()
print(f"Rows with 'price' <= 0: {invalid_price_count} ({invalid_price_count/len(df)*100:.2f}%)")

# Now we can safely drop those rows
df = df[df['price'] > 0]

Rows with 'price' <= 0: 6845 (20.96%)

In [11]:
# Now let's check for outliers
print(f"Price statistics:\n{df['price'].describe()}")

Price statistics:
count    25820.000000
mean       275.094578
std       1735.242095
min         11.000000
25%         93.000000
50%        133.000000
75%        200.000000
max      50000.000000
Name: price, dtype: float64

In [12]:
# Let's delete any rows where the price is above 1000
outlier_count = (df['price'] > 1000).sum()
print(f"Rows with 'price' > 1000: {outlier_count} ({outlier_count/len(df)*100:.2f}%)")

df = df[df['price'] <= 1000]

Rows with 'price' > 1000: 323 (1.25%)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 25497 entries, 0 to 32664
Data columns (total 70 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            25497 non-null  int64
 1   listing_url                                   25497 non-null  object
 2   last_searched                                 25497 non-null  object
 3   name                                          25497 non-null  object
 4   description                                   25092 non-null  object
 5   neighborhood_overview                         11073 non-null  object
 6   picture_url                                   25497 non-null  object
 7   host_id                                       25497 non-null  int64
 8   host_url                                      25497 non-null  object
 9   host_name                                     25492 non-null  object
 10  host_since                                    25492 non-null  object
 11  host_location                                 17121 non-null  object
 12  host_about                                    10118 non-null  object
 13  host_response_time                            23752 non-null  object
 14  host_response_rate                            23752 non-null  object
 15  host_acceptance_rate                          24541 non-null  object
 16  host_is_superhost                             25205 non-null  object
 17  host_thumbnail_url                            25492 non-null  object
 18  host_picture_url                              25492 non-null  object
 19  host_neighbourhood                            19249 non-null  object
 20  host_listings_count                           25492 non-null  float64
 21  host_total_listings_count                     25492 non-null  float64
 22  host_verifications                            25492 non-null  object
 23  host_has_profile_pic                          25492 non-null  object
 24  host_identity_verified                        25492 non-null  object
 25  neighbourhood                                 11073 non-null  object
 26  latitude                                      25497 non-null  float64
 27  longitude                                     25497 non-null  float64
 28  property_type                                 25497 non-null  object
 29  room_type                                     25497 non-null  object
 30  accommodates                                  25497 non-null  int64
 31  bathrooms                                     25469 non-null  float64
 32  bathrooms_text                                25454 non-null  object
 33  bedrooms                                      25440 non-null  float64
 34  beds                                          25475 non-null  float64
 35  amenities                                     25497 non-null  object
 36  price                                         25497 non-null  float64
 37  minimum_nights                                25497 non-null  int64
 38  maximum_nights                                25497 non-null  int64
 39  calendar_updated                              0 non-null      float64
 40  has_availability                              25308 non-null  object
 41  availability_30                               25497 non-null  int64
 42  availability_60                               25497 non-null  int64
 43  availability_90                               25497 non-null  int64
 44  availability_365                              25497 non-null  int64
 45  calendar_last_scraped                         25497 non-null  object
 46  number_of_reviews                             25497 non-null  int64
 47  number_of_reviews_ltm                         25497 non-null  int64
 48  number_of_reviews_l30d                        25497 non-null  int64
 49  availability_eoy                              25497 non-null  int64
 50  number_of_reviews_ly                          25497 non-null  int64
 51  estimated_occupancy_l365d                     25497 non-null  int64
 52  estimated_revenue_l365d                       25497 non-null  float64
 53  first_review                                  23029 non-null  object
 54  last_review                                   23029 non-null  object
 55  review_scores_rating                          23029 non-null  float64
 56  review_scores_accuracy                        23029 non-null  float64
 57  review_scores_cleanliness                     23029 non-null  float64
 58  review_scores_checkin                         23029 non-null  float64
 59  review_scores_communication                   23029 non-null  float64
 60  review_scores_location                        23029 non-null  float64
 61  review_scores_value                           23029 non-null  float64
 62  instant_bookable                              25497 non-null  object
 63  calculated_host_listings_count                25497 non-null  int64
 64  calculated_host_listings_count_entire_homes   25497 non-null  int64
 65  calculated_host_listings_count_private_rooms  25497 non-null  int64
 66  calculated_host_listings_count_shared_rooms   25497 non-null  int64
 67  region_name                                   25497 non-null  object
 68  region_parent_name                            25497 non-null  object
 69  reviews_per_month                             23029 non-null  float64
dtypes: float64(18), int64(19), object(33)
memory usage: 13.8+ MB

In [14]:

# Save the cleaned dataset to a new CSV file
df.to_csv('Ireland_Airbnb_Listing__Detailed__Investor.csv', index=False)